version: '3.8'

services:
  config-server:
    build:
      context: ./backend/config-server
    ports:
      - "8888:8888"
    networks:
      - myfinbank-network

  discovery-server:
    build:
      context: ./backend/discovery-server
    ports:
      - "8761:8761"
    networks:
      - myfinbank-network

  customer-service:
    build:
      context: ./backend/customer-service
    ports:
      - "8081:8080"
    networks:
      - myfinbank-network
    depends_on:
      - config-server
      - discovery-server

  account-service:
    build:
      context: ./backend/account-service
    ports:
      - "8082:8080"
    networks:
      - myfinbank-network
    depends_on:
      - config-server
      - discovery-server

  transaction-service:
    build:
      context: ./backend/transaction-service
    ports:
      - "8083:8080"
    networks:
      - myfinbank-network
    depends_on:
      - config-server
      - discovery-server

  frontend:
    build:
      context: ./frontend/angular-app
    ports:
      - "4200:4200"
    networks:
      - myfinbank-network

networks:
  myfinbank-network:
    driver: bridge