server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myfinbank/config-repo
          search-paths: '{application}'
      discovery:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka/
  datasource:
    url: jdbc:mysql://localhost:3306/myfinbank
    username: root
    password: password
  application:
    name: config-server
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG